tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            colors: {
                "surface-dim": "#dcd9d9",
                "surface": "#fcf9f8",
                "on-primary-fixed-variant": "#004f4f",
                "surface-container-high": "#eae7e7",
                "surface-bright": "#fcf9f8",
                "outline": "#74777d",
                "on-secondary": "#ffffff",
                "error-container": "#ffdad6",
                "surface-variant": "#e4e2e1",
                "tertiary-container": "#38260b",
                "tertiary-fixed-dim": "#e1c29b",
                "outline-variant": "#c4c6cd",
                "inverse-primary": "#76d6d5",
                "on-tertiary-fixed-variant": "#584326",
                "tertiary-fixed": "#feddb5",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed-dim": "#b7c8de",
                "on-tertiary-container": "#a88c69",
                "on-secondary-fixed-variant": "#38485a",
                "surface-tint": "#006a6a",
                "on-primary-fixed": "#002020",
                "inverse-on-surface": "#f3f0f0",
                "on-primary": "#ffffff",
                "secondary-fixed": "#d2e4fb",
                "surface-container-low": "#f6f3f2",
                "on-tertiary-fixed": "#281802",
                "on-error-container": "#93000a",
                "primary-fixed-dim": "#76d6d5",
                "surface-container": "#f0eded",
                "on-surface": "#1b1c1c",
                "on-error": "#ffffff",
                "secondary-container": "#d2e4fb",
                "on-secondary-fixed": "#0b1d2d",
                "primary": "#001919",
                "tertiary": "#211200",
                "secondary": "#4f6073",
                "inverse-surface": "#303030",
                "on-tertiary": "#ffffff",
                "on-surface-variant": "#44474c",
                "on-primary-container": "#3a9f9f",
                "on-background": "#1b1c1c",
                "background": "#fcf9f8",
                "error": "#ba1a1a",
                "on-secondary-container": "#556679",
                "primary-container": "#002f2f",
                "surface-container-highest": "#e4e2e1",
                "primary-fixed": "#93f2f2"
            },
            fontFamily: {
                "headline": ["Manrope"],
                "body": ["Inter"],
                "label": ["Inter"]
            },
            borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
        },
    },
};
